### PR TITLE
ci: build and push docker image to ghcr

### PR DESCRIPTION
**Pull request by jasonappah**

### CODE REVIEW

**Comment by cjdenio** [comment]
Maybe the `push` job should be in its own workflow if it only runs on `main` pushes?

**Comment by jasonappah** [comment]
That makes sense - should I go ahead and make the same changes on our other repos as well then?

**Comment by cjdenio** [comment]
Just update this repo to start

**Review by anirudhb — APPROVED** [review]
fwiw held off on approving this til we had something that was runnable

**Pull request merged**
